### ISSUE TITLE
The one tap modal jumps twice on android device if you close it

### ISSUE THREAD

**Issue by yakovyarmo** [inouiw/capacitor-native-google-one-tap-signin#16]
If I close the first modal by clicking the X the second pop up jumps.
This is bad ui practice

**Comment by inouiw** [comment]
Hi @yakovyarmo,
thank you for reporting the issue. I could reproduce that on android the auth screen was displayed again when cancelled.
It should be fixed in version 5.1.3.

So I close this issue.
