### ISSUE TITLE
One Tap for Android will be deprecated soon

### ISSUE THREAD

**Issue by naonao-a** [inouiw/capacitor-native-google-one-tap-signin#17]
Caution: One Tap for Android will be deprecated soon. To ensure the continued security and usability of your app, [migrate to Credential Manager](https://developer.android.com/training/sign-in/credential-manager) today. Credential Manager supports passkey, password, and federated identity authentication (such as Sign-in with Google), stronger security, and a more consistent user experience.

**Comment by naonao-a** [comment]
This is a warning from the developer platform. Android's one-click login will be deprecated soon. Unfortunately, I have not found a better library than this. I hope the author can update it. Thank you.

**Comment by naonao-a** [comment]
> Hi @naonao-a , thank you for the report. I am the author.
> 
> You are right. The code file [GoogleOneTapAuth.java](https://github.com/inouiw/capacitor-native-google-one-tap-signin/blob/main/android/src/main/java/com/proventask/capacitor/GoogleOneTapAuth/GoogleOneTapAuth.java) uses classes in the `com.google.android.gms.auth.api.signin` namespace as `GoogleSignIn`, `GoogleSignInAccount` and `GoogleSignInClient` which are depreciated.
> 
> However the code also already uses _Sign in with Google_. You can see in the [GoogleOneTapAuth.java](https://github.com/inouiw/capacitor-native-google-one-tap-signin/blob/main/android/src/main/java/com/proventask/capacitor/GoogleOneTapAuth/GoogleOneTapAuth.java) file that the classes `Identity` and `SignInClient` from the `com.google.android.gms.auth.api.identity` namespace are used to auto-sign-in the user. Sign-in using a button is using the depreciated way and needs to be updated as described in the link you mentioned.
> 
> I will try to release an updated version in the next 7 days.

OH!! that's very kind of you .Thank you.

**Comment by jamesgroat** [comment]
@naonao-a I also am interested in this update.

**Comment by inouiw** [comment]
@naonao-a, @jamesgroat,
the fix is now merged and there is a new npm package with version 6.0.0. The new package uses capacitor version 6. The android code was migrated from Java to Kotlin. Further the return type of tryAutoOrOneTapSignIn, tryOneTapSignIn and tryAutoSignIn was simplified to return just one promise instead of a promise containing promises. The documentation in the README is adjusted.

**Comment by naonao-a** [comment]
> @naonao-a, @jamesgroat, the fix is now merged and there is a new npm package with version 6.0.0. The new package uses capacitor version 6. The android code was migrated from Java to Kotlin. Further the return type of tryAutoOrOneTapSignIn, tryOneTapSignIn and tryAutoSignIn was simplified to return just one promise instead of a promise containing promises. The documentation in the README is adjusted.

Thank you so much.
