### ISSUE TITLE
Demo not working for iOS?

### ISSUE THREAD

**Issue by baylorpaul** [inouiw/capacitor-native-google-one-tap-signin#21]
After adding a `@ts-ignore` above`web.ts:204`, I was able to run the demo code in the web successfully. However, I was not able to run the iOS demo. I have made the corresponding client ID updates in `Info.plist` and `Page1.tsx`. Am I missing something?

As a side note, I have been using `@codetrix-studio/capacitor-google-auth` successfully in a project on web & iOS, but am trying to migrate to your library, which is more up to date. I say that to say I have successfully implemented an iOS version, so I'm not sure that it's an issue with `Info.plist`.

Thanks for working on this project!

**Comment by inouiw** [comment]
@baylorpaul thank you for reporting the bug.
It seems the capacitor version was not set correctly everywhere, also I updated GoogleSignIn and the capacitor dependency in the Podfile. Now it works for me. I published version 6.0.3.

Can you check if version 6.0.3 works for you?

**Comment by inouiw** [comment]
Also note, the first time you authenticate, it must be using the button. Then you can auto-sign-in.

**Comment by baylorpaul** [comment]
Thank you, that works! And thanks for the quick turnaround too.
