### ISSUE TITLE
Unable to login on android

### ISSUE THREAD

**Issue by jorgementx** [inouiw/capacitor-native-google-one-tap-signin#23]
The web version worked fine but the android version outputs the following error after pressing on the "sign-in with google button flow for native platforms" and selecting the desired google account.
![image](https://github.com/user-attachments/assets/bccc3b03-5197-4ef2-a841-533d3966962a)

Thank you in advance!

**Comment by inouiw** [comment]
Hi @jorgementx,
thank you for reporting the issue.
First I corrected a path in package.json related to android, but I do not think it is the cause of your issue.

It could be that "Google Play" is not up-to-date on the emulator. To update Google Play for the emulator from android studio you can do the following:
View -> Tool Windows -> Running Devices 
Click "Extended Controls"
A popup appears
Click "Google Play" -> "Update"
The Emulator asks you to sign in to your google account.
Sign in, confirm and then click "Update" to update Google Play services. If only "Uninstall" is shown, it is already up to date.

Maybe you can also try a physical device to see if it is working there.
On my Mac I do not get the error, but on a windows computer, where I just installed android stuidio, I also get it. I will check later this week to find a solution.

**Comment by jorgementx** [comment]
Thank you for your fast reply. However, I am already using a physical device (I was sharing the screen via `scrcpy` to my computer so it was easier to screenshot).
Thanks once again for your response!

**Comment by inouiw** [comment]
Did you create a OAuth 2.0 Client ID in the android developer console?

Quote from the readme:
For the android platform, you need to create a client ID of type "Android", as stated in [Set up your Google APIs console project](https://developer.android.com/identity/sign-in/credential-manager-siwg#set-google). You just need to create that client ID, you do not need to include it in any config. It is linked to your app via the package name and SHA-1 signing certificate fingerprint of your app. Note that usually the signing certificate for developments builds is different than for app store builds so you will need to create a client ID for development builds and one for app store builds.

**Comment by jorgementx** [comment]
For the demo app, I tried both creating a signed apk with a keystore and registering that SHA1 in the google cloud console and using the default SHA1 provided by Android Studio when executing the gradle task signingReport and registering it too in google cloud console. 
![image](https://github.com/user-attachments/assets/21f05adf-1406-42d1-bd45-5af86a025240)
![image](https://github.com/user-attachments/assets/3f38dec9-4b10-48df-9db3-d99759d2f0de)
![image](https://github.com/user-attachments/assets/0f274201-2301-4c16-be81-dd5c22f42059)
![image](https://github.com/user-attachments/assets/36eb3bdd-931a-4e16-97b6-b08493ca55a8)

And for my own app in the play store i just registered the one i use to sign the production app build.

I get the same error in all cases.

If you need to see some other configuration I'll be happy to share it with you.

**Comment by inouiw** [comment]
I have updated the plugin so that the package ID and the package SHA-1 is displayed in the error message if the authentication fails. Can you pull the latest version and verify the SHA-1 code?
For me, the android phone I have is giving no errors.

**Comment by jorgementx** [comment]
At first I thought that the reason might be that my google cloud app was not in production mode and verified, but they already verified it and the publish state is set to production.
![image](https://github.com/user-attachments/assets/ad50a260-4634-46c6-9af0-3d7441093fbc)

After pulling the last changes and the last version of the package I get the following error, where the package name and the SHA1 matches the one i sent in my last comment.
![image](https://github.com/user-attachments/assets/08ad4a00-cc5d-4177-b5c6-fce2f57c6b47)

I also tried to build a signed apk with the other keystore I mentioned and it shows the other SHA1 and the correct package name too.

**Comment by inouiw** [comment]
If you did not do it already, you could create your own "Web application" Clinet ID. This client-id used in the android code. Below a screenshot. Other than that I would go through the logcat messages without a filter so you can see all messages.![image](https://github.com/user-attachments/assets/7ef73c66-9eba-4eb0-9227-9d8c035c80f7)
