### ISSUE TITLE
exposing the button on click function for custom buttons

### ISSUE THREAD

**Issue by yakovyarmo** [inouiw/capacitor-native-google-one-tap-signin#8]
Hi,
I'm using you plugin and it is really amazing.
I just want to know if there is any chance that you can expose somehow the on click function so I can create custom button with the and attach the function from the plugin.
Thanks a lot

**Comment by inouiw** [comment]
Hi @yakovyarmo,
yes!
Google advises to use the button which the library generates. Which has the advantage that for the web the button shows the e-mail address of the user if there is an existing session.
However that way the design of the button cannot be adjusted much. Also I do not think there is much value in showing the e-mail address in the button as there is a popup anyway.

Recently I noticed that other websites that use google one tab, have their own button design and hide the google-generated button. For example medium.com or binance.com

So I am planning to support a custom button.
Will try to do it till the end of May.

**Comment by yakovyarmo** [comment]
Another problem with this approach is that it creates a one time button, because the promise will resolve only once.
If i'll click in it again it wont trigger the resolve then.

**Comment by inouiw** [comment]
> Another problem with this approach is that it creates a one time button, because the promise will resolve only once. If i'll click in it again it wont trigger the resolve then.

The behaviour should be that the promise resolves when you have the user credentials. Is that not working for you?

**Comment by inouiw** [comment]
I do not understand the problem yet.
The promise should only resolve if you successfully get the credential. So if you cancel the login you should be able to click the button again.
Or do you want to be able to click the button even if you login successfully?
I could imagine a use case where the user has several google accounts, selects the wrong one and wants to login with another account.

**Comment by yakovyarmo** [comment]
The last scenario.

**Comment by inouiw** [comment]
@yakovyarmo I added a new method `addSignInActionToExistingButton` to `branch feature-8-custom-button`. That method allows you to specify your own button for web, android and ios.
You need to pass the button-id and the id of the parent element which must have the style "position: 'relative'"

For the web platform, the implementation renders the google button invisible above the user-supplied button as done by https://accounts.binance.com/en/register.

Please check the commit. After that I will merge and push a new package version.

**Comment by yakovyarmo** [comment]
Great,
We are going to test it and let you know.

**Comment by inouiw** [comment]
Version 5.1.0, that contains the changes, is now published.
Will close this issue. Thank you for your feedback.
